export const listings = [
  {
    id: "1",
    title: "Modern Studio in Downtown",
    address: "245 W 14th St, Apt 3B",
    city: "New York, NY",
    price: 2150,
    beds: 1,
    baths: 1,
    sqft: 520,
    matchPercent: 92,
    demand: "High",
    image: "https://images.unsplash.com/photo-1559329146-807aff9ff1fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnQlMjBidWlsZGluZyUyMGV4dGVyaW9yfGVufDF8fHx8MTc3MjIzODA1OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    crimeIndex: 28,
    rentTrend: "+3.2%",
    neighborhoodRisk: "Low",
    scamScore: 2,
    timeLeft: "2h 15m",
    aiSuggestion: "Add guarantor → +12% acceptance",
    competitionScore: 78,
    features: ["In-unit W/D", "Rooftop", "Doorman"],
  },
  {
    id: "2",
    title: "Sunny 2BR Near Campus",
    address: "812 College Ave, Unit 4",
    city: "Austin, TX",
    price: 1450,
    beds: 2,
    baths: 1,
    sqft: 780,
    matchPercent: 82,
    demand: "Medium",
    image: "https://images.unsplash.com/photo-1737305467768-cfcbf106a535?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwc3R1ZGlvJTIwYXBhcnRtZW50JTIwaW50ZXJpb3J8ZW58MXx8fHwxNzcyMjUxNjU4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    crimeIndex: 15,
    rentTrend: "-1.1%",
    neighborhoodRisk: "Low",
    scamScore: 5,
    timeLeft: "4h 30m",
    aiSuggestion: "Upload bank statement → +8% acceptance",
    competitionScore: 54,
    features: ["Pet Friendly", "Parking", "Near Transit"],
  },
  {
    id: "3",
    title: "Urban Loft w/ City Views",
    address: "1920 Market St, Loft 7",
    city: "San Francisco, CA",
    price: 2800,
    beds: 1,
    baths: 1,
    sqft: 650,
    matchPercent: 74,
    demand: "Very High",
    image: "https://images.unsplash.com/photo-1759264244827-1dde5bee00a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMGxvZnQlMjBhcGFydG1lbnQlMjBsaXZpbmclMjByb29tfGVufDF8fHx8MTc3MjI1MTY1OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    crimeIndex: 42,
    rentTrend: "+5.8%",
    neighborhoodRisk: "Medium",
    scamScore: 8,
    timeLeft: "45m",
    aiSuggestion: "Increase deposit offer → +15% acceptance",
    competitionScore: 91,
    features: ["Gym", "Concierge", "City View"],
  },
  {
    id: "4",
    title: "Renovated Townhouse",
    address: "342 Elm Street",
    city: "Chicago, IL",
    price: 1850,
    beds: 3,
    baths: 2,
    sqft: 1200,
    matchPercent: 67,
    demand: "Low",
    image: "https://images.unsplash.com/photo-1758796629979-c967b99dec5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b3duaG91c2UlMjByZXNpZGVudGlhbCUyMG5laWdoYm9yaG9vZHxlbnwxfHx8fDE3NzIyNTE2NTl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    crimeIndex: 35,
    rentTrend: "+0.4%",
    neighborhoodRisk: "Medium",
    scamScore: 3,
    timeLeft: "1d 6h",
    aiSuggestion: "Add co-signer → +10% acceptance",
    competitionScore: 32,
    features: ["Backyard", "Garage", "Basement"],
  },
];

export const documents = [
  { id: "1", name: "Government ID", status: "verified", icon: "id" },
  { id: "2", name: "Proof of Income", status: "verified", icon: "income" },
  { id: "3", name: "Bank Statements", status: "pending", icon: "bank" },
  { id: "4", name: "Employment Letter", status: "verified", icon: "employment" },
  { id: "5", name: "Credit Report", status: "missing", icon: "credit" },
  { id: "6", name: "References", status: "verified", icon: "references" },
];

export const profileSuggestions = [
  {
    id: "1",
    action: "Upload last 3 months bank statements",
    impact: 15,
    category: "Financial",
    autoApplied: false,
  },
  {
    id: "2",
    action: "Add employer reference letter",
    impact: 12,
    category: "Employment",
    autoApplied: true,
  },
  {
    id: "3",
    action: "Complete credit authorization",
    impact: 18,
    category: "Credit",
    autoApplied: false,
  },
  {
    id: "4",
    action: "Add guarantor information",
    impact: 22,
    category: "Financial",
    autoApplied: false,
  },
  {
    id: "5",
    action: "Verify student enrollment status",
    impact: 8,
    category: "Identity",
    autoApplied: true,
  },
  {
    id: "6",
    action: "Link LinkedIn profile",
    impact: 5,
    category: "Identity",
    autoApplied: false,
  },
];
